### ISSUE TITLE
list_eq - c++

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-client-testing#27]
This test seems to want to fail on writing to the DB. I dont know what the issue is, as a a bst_eq test has no problem:

make list_eq
clang++ -g -o list_eq list_eq.cpp -g -I/Users/kalpathi/gr/bridges/client/cxx/bridges18/src/  -I/usr/local/curl760/include/  -I/usr/local/rapidjson/include/ -DTESTING=1 -std=c++11  -L/usr/local/curl760/lib/  -lcurl
!likalpathi-world% !list
list_eq 1103 bridges_testing 1321549621122 clone

Posting assignment to the server failed!
curl_easy_perform() failed.
Curl Error Code 22
HTTP response code said error
The requested URL returned error: 400 Bad Request
Possibly Bad BRIDGES Credentials

Provided Bridges Credentials:
	 User Name: bridges_testing
	 API Key: 1321549621122
	 Assignment Number: 1103

**Comment by esaule** [comment]
code 400 should indicate invalid JSON. unless there is another problem.

On January 4, 2019 5:41:15 PM EST, Kalpathi Subramanian <notifications@github.com> wrote:
>This test seems to want to fail on writing to the DB. I dont know what
>the issue is, as a a bst_eq test has no problem:
>
>make list_eq
>clang++ -g -o list_eq list_eq.cpp -g
>-I/Users/kalpathi/gr/bridges/client/cxx/bridges18/src/ 
>-I/usr/local/curl760/include/  -I/usr/local/rapidjson/include/
>-DTESTING=1 -std=c++11  -L/usr/local/curl760/lib/  -lcurl
>!likalpathi-world% !list
>list_eq 1103 bridges_testing 1321549621122 clone
>
>Posting assignment to the server failed!
>curl_easy_perform() failed.
>Curl Error Code 22
>HTTP response code said error
>The requested URL returned error: 400 Bad Request
>Possibly Bad BRIDGES Credentials
>
>
>Provided Bridges Credentials:
>	 User Name: bridges_testing
>	 API Key: 1321549621122
>	 Assignment Number: 1103
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/krs-world/Bridges_Testing/issues/27

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
