### ISSUE TITLE
python tests broken..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-client-testing#30]
So looks like the function names have been  changed and none of the tests work

setTitle --> set_title
setDescription --> set_description

etc.

Allie, so this should not be changed, since this is following python convention and is going to be a bit different from the C++/Java versions.

Can you undo your changes?  Work with Matthew to repair this.  All the tests are also now modified.

       -- krs

**Comment by quaiquai** [comment]
Try again, i fixed the calls

**Comment by Amarix** [comment]
Ack! I forgot that when I was copying them over yesterday sorry pulling it
up now!

**Comment by krs-world** [comment]
Still some errors:

File "/Users/kalpathi/gr/bridges/client/python/bridges18/bridges/graph_adj_matrix.py", line 194, in get_data_structure_representation
    nodes_JSON+=(nodes[k].get_element_representation())
  File "/Users/kalpathi/gr/bridges/client/python/bridges18/bridges/element.py", line 199, in get_element_representation
    if self.get_data_structure_type() == "KdTree":
AttributeError: 'Element' object has no attribute 'get_data_structure_type'
python mllist.py 3012 bridges_testing 1321549621122 clone
Visualization Description restricted to 250 Truncating description..

**Comment by krs-world** [comment]
Matthew is working on it looks like now..

**Comment by krs-world** [comment]
I think a good number of errors fixed..

**Comment by Amarix** [comment]
Yesterday I added the title and description to the Python classes and used
the c definitions to move them over quickly I removed the ; at the end but
hadn't realized the function call was different otherwise. Those are the
only changes made yesterday.


Are the test still not working? In the git im still seeing the format
bridges.settitle()

**Comment by Amarix** [comment]
Thanks Matthew!!

**Comment by quaiquai** [comment]
Youre welcome allie! KR, i pushed an update of bridges to the repo. The KDTree json generation had an extra comma in it, don't know how that got there but the visualization worked on my end.

**Comment by esaule** [comment]
long solved
