### ISSUE TITLE
shape collection test in java currently broken

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-client-testing#55]

**Comment by esaule** [comment]
See for instance: http://bridgesuncc.github.io/testing-logs/java_testing_logs.html#javalogshape_collection.java

**Comment by krs-world** [comment]
Fixed..

**Comment by krs-world** [comment]
fixed both shapecollection and shapecollection_layer tests.

**Comment by krs-world** [comment]
and shape collection text align..  all 3 should be good now.
